version: "3.4"

services:
  elasticsearch:
    image: elasticsearch:8.9.0
    container_name: elasticsearch
    restart: always
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    ports:
      - 9200:9200
      - 9300:9300

  fastapi:
    container_name: fastapi
    image: patdel
    restart: always
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000
    depends_on:
      - elasticsearch
