version: "3.8"

services:
  simple-search-app:
    build: .
    image: search_app:latest
    container_name: fastapi
    command:
      [
        "gunicorn",
        "main:app",
        "--bind",
        "0.0.0.0:8000",
        "--worker-class",
        "uvicorn.workers.UvicornWorker",
        "--workers",
        "4",
      ]
    ports:
      - 8000:8000
